baseURL = 'https://stevenh.pro/'
languageCode = 'en-us'
title = "Steven's Logfile"
theme = "PaperMod"
enableEmoji = true
enableRobotsTXT = true
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
disqusShortname = "spring28892"
hasCJKLanguage = true

[params]
author = "Steven Huang"
description = """
a.k.a spring28892
程式設計、法律、土木工程…諸多領域均略有涉略
以身為工具型選手為豪
並期望自己能在通才之路上更上一層樓
"""
copyright = "Steven Huang 2022 - {{ YEAR }}"
keywords = ""
mainSections = ["post"]
images = ['apple-touch-icon.png']
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = true

  homeInfoAvatar = "images/profile/profile.jpg"

  [params.homeInfoParams]
  Title = "Steven Huang"
  Content = """
a.k.a spring28892
程式設計、法律、土木工程…諸多領域均略有涉略
以身為工具型選手為豪
並期望自己能在通才之路上更上一層樓
"""

  [params.profileMode]
  enabled = false
  title = "Steven Huang"
  imageUrl = "images/profile/profile.jpg"
  imageTitle = "Steven Huang"

  [[params.socialIcons]]
  name = "linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/steven-huang/"

  [[params.socialIcons]]
  name = "github"
  title = "GitHub"
  url = "https://github.com/spring28892/"

  [[params.socialIcons]]
  name = "instagram"
  title = "instagram"
  url = "https://www.instagram.com/spring28892/"

  [[params.socialIcons]]
  name = "email"
  title = "e-mail"
  url = "mailto:spring28892@proton.me"

  [params.assets]
  favicon = "favicons/favicon.ico"
  favicon16x16 = "favicons/favicon-16x16.png"
  favicon32x32 = "favicons/favicon-32x32.png"
  apple_touch_icon = "favicons/apple-touch-icon.png"

  [params.cover]
  linkFullImages = true

[menu]

  [[menu.main]]
  name = "首頁"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "文章"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "專案作品"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "榮譽 & 成就"
  weight = 400
  identifier = "accomplishment"
  url = "/accomplishment/"

  [[menu.main]]
  name = "關於我"
  weight = 500
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "搜尋"
  weight = 600
  identifier = "search"
  url = "/search/"

  [[menu.main]]
  name = "彙整"
  weight = 700
  identifier = "archives"
  url = "/archives/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[outputs]
  home = ["HTML", "RSS", "JSON"]
